### ISSUE TITLE
Is there any better way to handle PhotoPane's state? 

### ISSUE THREAD

**Issue by darkamenosa** [ericvicenti/react-native-live#1]
In the "React Native Live: Building a Photo Viewer [Part 6]", I saw that we use a lot of "if else" to handle the PhotoPane's state. I was wondering if there is a better solution for this problem?

My first thought is using RxJS to handle some behavior like double tap and bit mask to handle the state.

**Comment by ericvicenti** [comment]
I think there are better options here, but for now lets focus on the usibilty other than the code quality
