### ISSUE TITLE
Using Closure to Log gestureState

### ISSUE THREAD

**Issue by geirman** [ericvicenti/react-native-live#8]
Hey Eric, sorry to clutter up your issues with this, but seemed like the best place to leave this.

During #9, around the 23rd minute, you were logging out gestureState using JSON.stringify() and I suggested using a closure. You mentioned that you didn't think it would make any difference, so I thought I'd do a little experiment to see. My results were strange, and not what I expected. I thought you might also find it interesting. 

I logged out gestureState three different ways (stringify, simple log, closure wrapped log)...
![2017-08-11_2240](https://user-images.githubusercontent.com/1640318/29238263-20a277e0-7ee6-11e7-9523-57b7af51bd92.png)

And interestingly enough, I got the same result regardless...
<img width="1238" alt="2017-08-11_2241" src="https://user-images.githubusercontent.com/1640318/29238266-47d240ca-7ee6-11e7-88dd-5449f1ef18cf.png">

So, I guess it really doesn't matter which way you do it in the end. 

Also, I'm sure you're aware of this already but noticed you haven't been using it. I think this is the best thing to come out in the react native debug narrative in a while...
https://www.npmjs.com/package/react-devtools

**Comment by ericvicenti** [comment]
Ah, good point! GestureState is not recycled but `e` may still be!
